#ifndef SISOP2_T1_CLIENTDEFINITIONS_H
#define SISOP2_T1_CLIENTDEFINITIONS_H

#define SUCCESSFUL_OPERATION 1
#define ERROR_SERVER_DISCONNECTED -69
#define ERROR_MAX_CONNECTIONS_PER_USERNAME_REACHED -100

#endif //SISOP2_T1_CLIENTDEFINITIONS_H
