#ifndef SISOP2_T1_CLIENTDEFINITIONS_H
#define SISOP2_T1_CLIENTDEFINITIONS_H

#define SUCCESSFUL_OPERATION 1
#define WRITING_FST_MESSAGE_ERROR -5
#define INVALID_HOST_ERROR -1
#define SOCKET_CREATION_ERROR -2
#define SOCKET_CONNECTION_ERROR -3

#endif //SISOP2_T1_CLIENTDEFINITIONS_H
