#ifndef SISOP2_T1_FRONTDEFINITIONS_H
#define SISOP2_T1_FRONTDEFINITIONS_H

#define PORT_FRONT 30000
#define PORT_SERVER 2000

#define SUCCESSFUL_OPERATION 1

#define ERROR_SOCKET_BINDING -1
#define ERROR_SOCKET_ACCEPT_CONNECTION -2
#define ERROR_INVALID_HOST -3
#define ERROR_SOCKET_CONNECTION -4
#define ERROR_CLIENT_DISCONNECTED -5

#endif //SISOP2_T1_FRONTDEFINITIONS_H
