#ifndef SISOP2_T1_FRONTDEFINITIONS_H
#define SISOP2_T1_FRONTDEFINITIONS_H

#define SUCCESSFUL_OPERATION 1

#define ERROR_SOCKET_BINDING -1
#define ERROR_SOCKET_ACCEPT_CLIENT_CONNECTION -2
#define ERROR_CLIENT_DISCONNECTED -6

#endif //SISOP2_T1_FRONTDEFINITIONS_H
