#ifndef SISOP2_T1_SERVERDEFINITIONS_H
#define SISOP2_T1_SERVERDEFINITIONS_H

#define MAX_CONNECTIONS_COUNT 2

#define SUCCESSFUL_OPERATION 1

#define ERROR_SOCKET_BINDING -2
#define ERROR_SOCKET_ACCEPT_CONNECTION -3
#define ERROR_SOCKET_CLOSE -4

#define ERROR_GROUP_NOT_FOUND -17
#define MAX_USER_CONNECTIONS_REACHED -20
#define ERROR_CLIENT_DISCONNECTED -134

#endif //SISOP2_T1_SERVERDEFINITIONS_H
